---
abstract: 'uri-based session state'
author:
  - 'Shinichiro Aska <s.aska.org {at} gmail.com>'
build_requires:
  HTTP::Request::Common: 0
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.2, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Session-State-URI
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Plack::Session::State::URI:
    file: lib/Plack/Session/State/URI.pm
    version: 0.05
requires:
  HTML::StickyQuery: 0
  Plack: 0
  Plack::Middleware::Session: 0
resources:
  bugtracker: https://github.com/s-aska/p5-Plack-Session-State-URI/issues
  homepage: https://github.com/s-aska/p5-Plack-Session-State-URI
  repository: git://github.com/s-aska/p5-Plack-Session-State-URI.git
version: 0.05
x_authority: cpan:ASKADNA
x_contributors:
  - 'Steffen Schwigon <ss5@renormalist.net>'
  - 'Shinichiro Aska <s.aska.org@gmail.com>'
