---
abstract: 'uri-based session state'
author:
  - 'Shinichiro Aska <s.aska.org {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Session-State-URI
no_index:
  directory:
    - inc
    - t
requires:
  HTML::StickyQuery: 0
  Plack: 0
  Plack::Middleware::Session: 0
resources:
  license: http://dev.perl.org/licenses
  repository: https://github.com/s-aska/p5-Plack-Session-State-URI
version: 0.02
